package com.jsonyao.xatest.db143.dao;

import com.jsonyao.xatest.db143.model.XA143;
import com.jsonyao.xatest.db143.model.XA143Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XA143Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    long countByExample(XA143Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int deleteByExample(XA143Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int insert(XA143 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int insertSelective(XA143 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    List<XA143> selectByExample(XA143Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    XA143 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int updateByExampleSelective(@Param("record") XA143 record, @Param("example") XA143Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int updateByExample(@Param("record") XA143 record, @Param("example") XA143Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int updateByPrimaryKeySelective(XA143 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_143
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    int updateByPrimaryKey(XA143 record);
}