package com.jsonyao.atomikos.db143.model;

public class XA143 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_143.id
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xa_143.name
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_143.id
     *
     * @return the value of xa_143.id
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_143.id
     *
     * @param id the value for xa_143.id
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xa_143.name
     *
     * @return the value of xa_143.name
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xa_143.name
     *
     * @param name the value for xa_143.name
     *
     * @mbg.generated Mon Feb 15 11:12:45 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}