package com.jsonyao.xatest.db142.dao;

import com.jsonyao.xatest.db142.model.XA142;
import com.jsonyao.xatest.db142.model.XA142Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface XA142Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    long countByExample(XA142Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int deleteByExample(XA142Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int insert(XA142 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int insertSelective(XA142 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    List<XA142> selectByExample(XA142Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    XA142 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int updateByExampleSelective(@Param("record") XA142 record, @Param("example") XA142Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int updateByExample(@Param("record") XA142 record, @Param("example") XA142Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int updateByPrimaryKeySelective(XA142 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xa_142
     *
     * @mbg.generated Mon Feb 15 11:11:15 CST 2021
     */
    int updateByPrimaryKey(XA142 record);
}